name: CI/CD Pipeline for Odoo 17

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget git python3-dev python3-pip build-essential libxslt1-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less libjpeg-dev libpq-dev

      - name: Create a virtual environment
        run: |
            python -m venv /opt/odoo/odoo-venv
            source /opt/odoo/odoo-venv/bin/activate
            pip install --upgrade pip  
            pip install wheel cryptography  

     

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 103.19.4.104 >> ~/.ssh/known_hosts

      - name: Deploy to Odoo Server
        run: |
         scp -r ./addons/account_move_multi_cancel root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/advance_cash_flow_statements root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/advanced_project_management_system root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/app_menu_alphabetical_order root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/auto_daily_weekly_report root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/base_account_budget root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/base_accounting_kit root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/bi_sms_client_generic root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/chatgpt_support_chatter root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/contact_documents root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/contacts_birthday_greetings root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/database_delete_protection root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/developer_mode root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/document_approval root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/dropbox_integration root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/easy_chatgpt_access root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/education_core root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/education_theme root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/event root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/event_management root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/event_registration_cancel_reason root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/event_registration_partner_unique root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/google_analytics_odoo root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/import_bank_statement_odoo root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/insurance_management_cybro root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/invoice_merging root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/LDAP-Reset-Password-main root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/mail_push_notification root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/master_search root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/membership root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/Membership_rotary_modification-main root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/multiple_payment_for_outstanding_dues root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/odoo_dynamic_dashboard root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/odoo_google_meet_integration root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/odoo_readonly_user root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/odoo_website_helpdesk root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/openai_odoo_base root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/partner_emails_history root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/partner_event root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/print_minutes_of_meeting root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/project_dashboard_odoo root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/project_progress_bar root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/projects_task_checklists root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/public_helpdesk-main root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/reset_journal_entries root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/restrict_web_debug root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/Rotary_project_map-main root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/schedule_activity_to_multiple_users root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/size_restriction_for_attachments root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/subscription_package root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/trial_balance_pdf root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/upload_multi_document root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/user_login_alert root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/volunteers_donors_management root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/website_event root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/website_floating_whatsapp_icon root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/website_gdpr_odoo root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/website_google_tag_manager root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/website_pdf_preview_snippet root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/whatsapp_mail_messaging root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/user_audit root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/hide_menu_user root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         scp -r ./addons/login_user_detail root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
         


      - name: Install Python dependencies on Odoo server
        run: |
          ssh root@103.19.4.104 'pip3 install openpyxl qifparse pyfcm httpagentparser dropbox pyncclient nextcloud-api-wrapper boto3 paramiko'
          
      #- name: Update Odoo Database
      #  run: |
       #   ssh root@103.19.4.104 "sudo -u odoo /odoo-venv/bin/python /opt/odoo/odoo-bin -c /opt/odoo/debian/odoo.conf -d Not4ProfitOrganisation -u all
        #  "

      - name: Start Odoo Server
        run: |
          ssh root@103.19.4.104 "sudo systemctl start odoo"
