name: CI/CD Pipeline for odoo17

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 103.19.4.104 >> ~/.ssh/known_hosts

      - name: Stop Odoo Server
        run: |
            ssh root@103.19.4.104 "sudo systemctl stop odoo || sudo pkill -f '/opt/odoo/odoo-bin'"
        
      - name: Deploy to Odoo Server
        run: |
            rsync -avz --delete --exclude='.git*' . root@103.19.4.104:/opt/odoo/addons/Not4Profit.online
             
            
      - name: Deploy DMS to Odoo Server
        run: |
            rsync -avz --delete --exclude='.git*' ./addons/dms/ root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/dms/


      #- name: Deploy to Odoo Server
       # run: |
       #    rsync -avz --exclude='.git*' . root@103.19.4.104:/opt/odoo/addons/Not4Profit.online

      #- name: Deploy DMS to Odoo Server
       # run: |
        #    rsync -avz --exclude='.git*' ./addons/dms/ root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/dms/


        
      - name: Start Odoo Server #just edit this
        run: |
            ssh root@103.19.4.104 "sudo systemctl start odoo"
        