name: CI/CD Pipeline for Odoo 17

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Install dependencies
       # run: |
       #   pip install -r requirements.txt 

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 103.19.4.104 >> ~/.ssh/known_hosts

     # - name: Stop Odoo Server
     #   run: |
     #     ssh root@103.19.4.104 "sudo systemctl stop odoo || sudo pkill -f '/opt/odoo/odoo-bin'"

      - name: Deploy to Odoo Server
        run: |
          scp -r ./addons/* root@103.19.4.104:/opt/odoo/addons/Not4Profit.online/addons/
          
      #- name: Update Odoo Database
      #  run: |
       #   ssh root@103.19.4.104 "sudo -u odoo /odoo-venv/bin/python /opt/odoo/odoo-bin -c /opt/odoo/debian/odoo.conf -d Not4ProfitOrganisation -u all
        #  "

      - name: Start Odoo Server
        run: |
          ssh root@103.19.4.104 "sudo systemctl start odoo"
