name: Deploy Odoo Modules

on:
  push:
    branches:
      - main # You can change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Odoo 17 uses Python 3.8

    

    - name: Install system dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y wget git python3-dev python3-pip build-essential libxslt1-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less libjpeg-dev libpq-dev

      

    - name: Install wkhtmltopdf
      run: |
            wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
            sudo apt install -y ./wkhtmltox_0.12.5-1.bionic_amd64.deb
  
    - name: List files to check if requirements.txt exists
      run: |
              echo "Current Directory: $(pwd)"
              echo "Listing files in /opt/odoo"
              ls -la /opt/odoo
              echo "Listing files in the root directory"
              ls -la / 

    - name: Install Odoo dependencies
      run: |
            pip install wheel
            pip install cryptography
            pip install -r /opt/odoo/requirements.txt  # Make sure to use the correct path



    - name: Update Repository on Server
      run: |
          ssh -o StrictHostKeyChecking=no root@103.19.4.104 'cd /opt/odoo/addons/Not4Profit.online && git pull origin main'
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Restart Odoo
      run: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@103.19.4.104 'sudo systemctl restart odoo'
      env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
