name: Odoo Module Deployment

on:
  push:
    branches:
      - main  # Trigger pipeline on push to the main branch (adjust as necessary)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Odoo server
      run: |
        ssh -o StrictHostKeyChecking=no root@103.19.4.104 "
        cd /opt/odoo/addons &&
        git clone https://github.com/Not4Profit-lab/Not4Profit.online.git &&
        systemctl restart odoo"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
