name: CI/CD Pipeline for Odoo 17

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget git python3-dev python3-pip build-essential libxslt1-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less libjpeg-dev libpq-dev

      - name: Install wkhtmltopdf
        run: |
          wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
          sudo apt install -y ./wkhtmltox_0.12.5-1.bionic_amd64.deb

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with: 
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add SSH Known Hosts
        run: |
          ssh-keyscan -H 103.19.4.104 >> ~/.ssh/known_hosts

      - name: Deploy updated modules to Odoo server
        run: |
          scp -r addons/event root@103.19.4.104:/opt/odoo/addons/
         

      # You can add additional steps here if necessary, but avoid the pip install step if not required

      # Optional: Restart Odoo server if needed
      - name: Restart Odoo server
        run: |
          ssh root@103.19.4.104 'sudo systemctl restart odoo'
