name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 103.19.4.104 >> ~/.ssh/known_hosts

      - name: Deploy to Odoo Server
        run: |
          rsync -avz --delete --exclude='.git*' . root@103.19.4.104:/opt/odoo/addons/Not4Profit.online
          ssh root@103.19.4.104 "cd /opt/odoo/addons/Not4Profit.online && ./update.sh"
